const $=s=>document.querySelector(s),M=MotorModel;
let config={...M.defaults},interventions=M.matched(config),data=[],playing=false,clock=12,lastTime=0,chartCache={},lastMatched=true;
const types=['force','stators','load'],colors=['#5ce0ce','#79aaff','#ffc67c'],names=['駆動力低下','固定子減少','負荷増加'];
const specs={voltage:['膜電位差 V',0,220,5,'mV'],dpH:['ΔpH（内 − 外）',-1,2,.1,''],diameter:['ビーズ直径',.2,1.2,.05,'μm'],radius:['回転半径',.1,.8,.05,'μm'],viscosity:['粘度',.5,5,.1,'mPa s'],tau:['固定子交換の時定数',.2,5,.2,'s'],fps:['撮影速度',30,2000,10,'fps'],exposure:['露光時間',.05,10,.05,'ms'],noise:['位置ノイズ σ',0,40,1,'nm']};
function number(x,d=1){return Number.isFinite(x)?x.toFixed(d):'—'}
function controls(keys){return keys.map(k=>{let [label,min,max,step,unit]=specs[k];return `<div class="field"><label for="${k}">${label}<output id="${k}Out"></output></label><input id="${k}" type="range" min="${min}" max="${max}" step="${step}" value="${config[k]}"></div>`}).join('')}
$('#baseControls').innerHTML=controls(['voltage','dpH','diameter','radius','viscosity','tau']);$('#cameraControls').innerHTML=controls(['fps','exposure','noise']);
$('#lanes').innerHTML=types.map((t,i)=>`<article class="lane" style="--accent:${colors[i]}"><span class="tag">CONDITION 0${i+1}</span><h3>${names[i]}</h3><div class="speed" id="speed${i}"></div><span class="tag">モデル速度（ドリフト）</span><canvas id="view${i}" width="360" height="325" role="img" aria-label="${names[i]}のモーターとビーズ像"></canvas><div class="stats" id="stats${i}"></div><div class="adjust"><label for="adjust${i}">${['駆動力の残存率','目標平均固定子数','粘度の倍率'][i]}<output id="adjustOut${i}"></output></label><input id="adjust${i}" type="range" min="${[.1,0,1][i]}" max="${[1,11,12][i]}" step="${[.01,.1,.05][i]}"></div><div class="warning" id="warning${i}"></div></article>`).join('');
function syncControls(){Object.keys(specs).forEach(k=>{$('#'+k).value=config[k];$('#'+k+'Out').textContent=config[k]+' '+specs[k][4]});$('#target').value=config.target;$('#targetOut').textContent=config.target+' %';$('#stochastic').checked=config.stochastic;$('#thermal').checked=config.thermal;types.forEach((t,i)=>{$('#adjust'+i).max=Math.max([1,11,12][i],interventions[t]);$('#adjust'+i).value=interventions[t];$('#adjustOut'+i).textContent=i===0?number(interventions[t]*100,0)+' %':number(interventions[t],2)+(i===2?' ×':' 個')});$('#exposureNote').textContent=`実効露光 ${number(Math.min(config.exposure,1000/config.fps),2)} ms（フレーム間隔以内）。ノイズは各座標の標準偏差。`}
function lateSpeed(d){return average(d.frames.filter(f=>f.t>=15&&f.t<20).map(f=>f.speed))}
function renderMatchStatus(){const el=$('#matchStatus'),baseline=M.speed(8,M.pmf(config)/180,M.drag(config)),target=baseline*config.target/100;
 if(baseline===0){el.textContent=I18n.t('内向き駆動力が0のため、基準速度は0です。3原因の比較は成立しません。');el.classList.add('warning-state');return}
 const actual=data.map(lateSpeed),deviation=Math.max(...actual.map(f=>Math.abs(f-target)/target));
 el.classList.toggle('warning-state',deviation>.05);
 el.textContent=`${I18n.t('基準 ')}${number(baseline)} Hz → ${I18n.t('目標 ')}${number(target)} Hz. ${I18n.t('15–20秒のモデル平均（駆動力・固定子・負荷）：')}${actual.map(f=>number(f)).join(' / ')} Hz. ${deviation>.05?I18n.t('実現速度に差があります。確率的交換や手動設定を確認してください。'):''}${!lastMatched?' '+I18n.t('現在の介入設定を保持しています。「同じ速度に揃える」で再設定できます。'):''}`;
}
function recompute(match=true){playing=false;lastMatched=match;$('#play').textContent='再生';if(match)interventions=M.matched(config);syncControls();data=types.map((type,i)=>M.simulate(config,interventions[type],type,12345+i*11111));chartCache={};renderSummary();renderMatchStatus();render();}
Object.keys(specs).forEach(k=>$('#'+k).addEventListener('input',e=>{$('#'+k+'Out').textContent=+e.target.value+' '+specs[k][4]}));
Object.keys(specs).forEach(k=>$('#'+k).addEventListener('change',e=>{config[k]=+e.target.value;recompute(!['fps','exposure','noise','tau'].includes(k))}));
$('#target').oninput=e=>{$('#targetOut').textContent=e.target.value+' %'};$('#target').onchange=e=>{config.target=+e.target.value;recompute()};
['stochastic','thermal'].forEach(k=>$('#'+k).onchange=e=>{config[k]=e.target.checked;recompute(false)});
types.forEach((t,i)=>{$('#adjust'+i).oninput=e=>{$('#adjustOut'+i).textContent=i===0?number(+e.target.value*100,0)+' %':number(+e.target.value,2)+(i===2?' ×':' 個')};$('#adjust'+i).onchange=e=>{interventions[t]=+e.target.value;recompute(false)}});
$('#match').onclick=()=>recompute();$('#reset').onclick=()=>{config={...M.defaults};clock=12;recompute()};
$('#play').onclick=()=>{if(clock>=30)clock=0;playing=!playing;$('#play').textContent=playing?'一時停止':'再生'};
$('#restart').onclick=()=>{clock=0;render()};$('#time').oninput=e=>{clock=+e.target.value;render()};$('#metric').onchange=drawChart;
$('#modelButton').onclick=()=>$('#model').showModal();$('#closeModel').onclick=()=>$('#model').close();
function current(d){return d.frames[Math.min(d.frames.length-1,Math.round(clock*config.fps))]}
function render(){ $('#time').value=clock;$('#timeOut').textContent=number(clock,2)+' s';data.forEach((d,i)=>{const f=current(d);$('#speed'+i).innerHTML=number(f.speed)+' <small>Hz</small>';$('#stats'+i).innerHTML=`<span>カメラ推定（1フレーム差）</span><span>${f.measured===null?'欠測':number(f.measured)+' Hz'}</span><span>固定子数</span><span>${number(f.n,config.stochastic?0:2)}</span><span>駆動力</span><span>${number(f.pmf)} mV</span><span>回転抵抗 ζ</span><span>${number(f.drag,2)}</span>`;$('#warning'+i).textContent=f.contrast<.15?'露光で像がリング化：速度推定は欠測。':f.speed>config.fps/2?'撮影速度不足：折り返しで逆回転や減速に見えます。':config.noise/(1000*config.radius)>.15?'位置ノイズが回転半径に対して大きい条件です。':f.measured===null?'速度推定なし：最初または直前のフレームが無効です。':' ';drawView(d,i,f)});drawChart();renderTorque()}
function circle(ctx,x,y,r,fill){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill()}
function drawView(d,i,f){const c=$('#view'+i),ctx=c.getContext('2d'),color=colors[i];ctx.clearRect(0,0,c.width,c.height);
 ctx.fillStyle='#91a8c4';ctx.font='12px system-ui';ctx.fillText('MOTOR · 1/100 SPEED',12,19);
 const angle=d.angleAt(clock)/100;
 ctx.fillStyle='#173248';ctx.fillRect(45,58,270,16);ctx.strokeStyle='#40617a';ctx.beginPath();ctx.moveTo(45,58);ctx.lineTo(315,58);ctx.moveTo(45,74);ctx.lineTo(315,74);ctx.stroke();
 // Fixed projected ring; subunit coordinates revolve in depth, never rotate the ellipse.
 ctx.fillStyle='#12373c';ctx.beginPath();ctx.ellipse(180,98,66,22,0,0,Math.PI*2);ctx.fill();
 const units=Array.from({length:28},(_,k)=>{let a=k*Math.PI*2/28-angle;return {x:180+66*Math.cos(a),z:Math.sin(a)}}).sort((a,b)=>a.z-b.z);
 function drawUnit(u){ctx.globalAlpha=.45+.5*(u.z+1)/2;ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(u.x,98+22*u.z,4.3+.6*u.z,9+u.z,0,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
 units.filter(u=>u.z<0).forEach(drawUnit);ctx.fillStyle='#8cbdcb';ctx.fillRect(175,46,10,60);units.filter(u=>u.z>=0).forEach(drawUnit);
 for(let k=0;k<11;k++){const a=k*Math.PI*2/11,x=180+89*Math.cos(a),y=96+30*Math.sin(a);ctx.fillStyle=k<Math.floor(f.n)?'#e4b979':'#223247';ctx.fillRect(x-4,y-6,8,12)}
 ctx.fillStyle='#91a8c4';ctx.fillText('CAMERA · EXPOSURE INTEGRATED',12,157);ctx.fillStyle='#060d17';ctx.fillRect(12,164,336,147);ctx.strokeStyle='#23324a';ctx.beginPath();ctx.arc(180,238,49,0,Math.PI*2);ctx.stroke();
 const samples=80,lo=Math.max(0,f.t-d.exposure);for(let j=0;j<samples;j++){const a=d.angleAt(lo+(f.t-lo)*j/(samples-1));const x=180+49*Math.cos(a),y=238-49*Math.sin(a);const g=ctx.createRadialGradient(x,y,0,x,y,9);g.addColorStop(0,'rgba(207,245,255,0.1)');g.addColorStop(1,'rgba(122,194,255,0)');circle(ctx,x,y,9,g)}
 // Small cross marks noisy centroid, not true instantaneous bead position.
 const x=180+49*f.x,y=238-49*f.y;ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(x-4,y);ctx.lineTo(x+4,y);ctx.moveTo(x,y-4);ctx.lineTo(x,y+4);ctx.stroke();ctx.fillStyle='#8ca0b9';ctx.font='11px system-ui';ctx.fillText(I18n.t('＋ 推定重心'),23,299);
}
function drawChart(){if(!data.length)return;const canvas=$('#chart'),ctx=canvas.getContext('2d'),key=$('#metric').value,w=canvas.width,h=canvas.height,L=70,R=20,T=20,B=40;ctx.clearRect(0,0,w,h);let min=0,max=0;
 const series=chartCache[key]??(chartCache[key]=data.map(d=>{let points=[];const bin=Math.max(1,Math.round(config.fps/20));for(let i=0;i<d.frames.length;i+=bin){let vals=d.frames.slice(i,i+bin).map(f=>f[key]).filter(v=>v!==null&&Number.isFinite(v));points.push([d.frames[i].t,vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null])}return points}));
 series.flat().forEach(([,v])=>{if(v!==null){min=Math.min(min,v);max=Math.max(max,v)}});max=Math.max(max,1);const pad=(max-min)*.08;max+=pad;if(min<0)min-=pad;const x=t=>L+t/30*(w-L-R),y=v=>T+(max-v)/(max-min)*(h-T-B);
 ctx.fillStyle='#193147';ctx.fillRect(x(5),T,x(20)-x(5),h-T-B);ctx.font='13px system-ui';ctx.lineWidth=1;for(let i=0;i<=4;i++){let v=min+(max-min)*i/4;ctx.strokeStyle='#29394e';ctx.beginPath();ctx.moveTo(L,y(v));ctx.lineTo(w-R,y(v));ctx.stroke();ctx.fillStyle='#a6b7cd';ctx.fillText(number(v,key==='n'?1:0),5,y(v)+4)}for(let t=0;t<=30;t+=5){ctx.fillStyle='#a6b7cd';ctx.fillText(t+' s',x(t)-10,h-12)}
 series.forEach((points,i)=>{ctx.strokeStyle=colors[i];ctx.lineWidth=2;ctx.beginPath();let pen=false;points.forEach(([t,v])=>{if(v===null){pen=false;return}if(pen)ctx.lineTo(x(t),y(v));else{ctx.moveTo(x(t),y(v));pen=true}});ctx.stroke()});ctx.strokeStyle='#d5e4f6';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(x(clock),T);ctx.lineTo(x(clock),h-B);ctx.stroke();ctx.setLineDash([]);
 $('#plotNote').textContent=key==='measured'?'カメラ推定速度の区間平均。欠測は除外。露光のぼけ・折り返しは補正していません。':'区間平均。背景の帯は介入期間、縦線は選択時刻。色は上の3条件に対応します。';$('#plotNote').textContent+=' '+I18n.t('平均区間 ')+number(Math.max(1,Math.round(config.fps/20))/config.fps*1000,1)+' ms';
}
function average(values){return values.length?values.reduce((a,b)=>a+b,0)/values.length:NaN}
function renderSummary(){const windows=data.map(d=>d.frames.filter(f=>f.t>=15&&f.t<20));const rows=[['真の平均速度 / Hz',f=>f.speed],['カメラ平均速度 / Hz',f=>f.measured],['平均固定子数',f=>f.n],['平均駆動力 / mV',f=>f.pmf],['平均抵抗 / pN nm s',f=>f.drag],['平均トルク / pN nm',f=>f.torque],['カメラ有効率 / %',f=>f.measured===null?0:100]];$('#summary').innerHTML=rows.map(([label,fn])=>`<tr><td>${label}</td>${windows.map(win=>`<td>${number(average(win.map(fn).filter(v=>v!==null)),2)}</td>`).join('')}</tr>`).join('')}
$('#csv').onclick=()=>{const columns=['condition','time_s','true_speed_Hz','camera_speed_Hz','stators','pmf_mV','drag_pN_nm_s','torque_pN_nm','contrast','x_over_radius','y_over_radius','fps','effective_exposure_ms','noise_nm','seed','voltage_mV','delta_pH','bead_diameter_um','orbit_radius_um','viscosity_mPa_s','exchange_tau_s','stochastic','thermal','intervention_value','model','knee_speed_ratio','knee_torque_ratio'];let lines=[columns.join(',')];data.forEach((d,i)=>d.frames.forEach(f=>lines.push([d.type,f.t,f.speed,f.measured??'',f.n,f.pmf,f.drag,f.torque,f.contrast,f.x,f.y,config.fps,d.exposure*1000,config.noise,12345+i*11111,config.voltage,config.dpH,config.diameter,config.radius,config.viscosity,config.tau,config.stochastic,config.thermal,d.intervention,M.curve.id,M.curve.kneeSpeedRatio,M.curve.kneeTorqueRatio].join(','))));const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='flagellascope-comparison.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function tick(now){if(playing){clock=Math.min(30,clock+Math.min(.1,(now-lastTime)/1000));render();if(clock>=30){playing=false;$('#play').textContent='再生'}}lastTime=now;requestAnimationFrame(tick)}
recompute();requestAnimationFrame(tick);
const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort());
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_motor_comparison',description:'Set the target speed percentage and stochastic stator option, recompute all three visible experiments, and return late intervention mean speeds.',inputSchema:{type:'object',properties:{target_percent:{type:'number',minimum:25,maximum:90},stochastic:{type:'boolean'}},required:['target_percent'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).some(k=>!['target_percent','stochastic'].includes(k))||!Number.isFinite(input.target_percent)||input.target_percent<25||input.target_percent>90||('stochastic'in input&&typeof input.stochastic!=='boolean'))throw Error('Invalid experiment parameters');config.target=input.target_percent;if('stochastic'in input)config.stochastic=input.stochastic;recompute();return {target_percent:config.target,mean_speeds_Hz:data.map(d=>({condition:d.type,speed:average(d.frames.filter(f=>f.t>=15&&f.t<20).map(f=>f.speed))}))}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
