const I18n=(()=>{
 let language='en';const saved=new WeakMap(),attrs=new WeakMap();
 const pairs=[
 ['モデルと仮定','Model & assumptions'],['同じ速度低下。異なる原因。','Same slowdown. Different causes.'],['イオン駆動力・固定子交換・負荷を、同じビーズ実験で比較する。','Compare ion motive force, stator exchange and load in the same bead assay.'],['H⁺駆動・仮説検討用モデル','H⁺-driven · hypothesis exploration'],['実験条件','Experiment settings'],['初期値','Reset defaults'],['介入後の目標速度','Target speed after intervention'],['基準の固定子数は8。5秒で介入、20秒で解除。3条件の定常平均場速度を揃えます。','Baseline: 8 stators. Intervention at 5 s, release at 20 s. Match steady-state mean-field speeds.'],['3つの原因を同じ速度に揃える','Match speed across all three causes'],['固定子交換を確率的にする','Stochastic stator exchange'],['回転の熱ゆらぎを加える','Include thermal angular fluctuations'],['同じ乱数シードで再計算。基準区間の固定子数は8に固定します。','Recompute with the same random seeds. Baseline stator count is fixed at 8.'],['一時停止','Pause'],['再生','Play'],['先頭へ','Rewind'],['時刻','Time'],['CSV保存','Export CSV'],['0–5 s 基準','0–5 s Baseline'],['5–20 s 介入','5–20 s Intervention'],['20–30 s 回復','20–30 s Recovery'],['原因を見分ける観測量','Measurements that distinguish causes'],['同じ速度でも、ここが違う','What differs at the same speed'],['介入終盤 15–20 s','Late intervention: 15–20 s'],['速度だけでは原因を一意に決められません。固定子蛍光、駆動力の指標、負荷の校正を組み合わせる仮想実験です。比較表はシミュレーター内部の真値を含みます。','Speed alone does not identify a unique cause. Combine stator fluorescence, motive-force indicators and calibrated load. This table includes internal model values.'],['計算式と適用範囲','Equations and scope'],['駆動力と力学','Motive force and mechanics'],['同じ速度への自動設定','Automatic speed matching'],['固定子の交換','Stator exchange'],['観察モデル','Observation model'],['閉じる','Close'],['時系列の表示項目','Time-series variable'],['3条件の時系列比較','Time-series comparison of three conditions'],
 ['膜電位差 V','Membrane potential V'],['ΔpH（内 − 外）','ΔpH (inside − outside)'],['ビーズ直径','Bead diameter'],['回転半径','Orbit radius'],['固定子交換の時定数','Stator exchange time constant'],['撮影速度','Frame rate'],['露光時間','Exposure time'],['位置ノイズ σ','Position noise σ'],['粘度','Viscosity'],
 ['駆動力低下','Reduced motive force'],['固定子減少','Fewer stators'],['負荷増加','Increased load'],['真の瞬時速度','Model drift speed'],['のモーターとビーズ像',' motor and bead view'],['駆動力の残存率','Remaining motive force'],['目標平均固定子数','Target mean stator count'],['粘度の倍率','Viscosity multiplier'],[' 個',' stators'],['実効露光 ','Effective exposure '],[' ms（フレーム間隔以内）。ノイズは各座標の標準偏差。',' ms (capped at the frame interval). Noise is the SD of each coordinate.'],['内向き駆動力が0のため、基準速度は0です。','Inward motive force is zero; baseline speed is zero.'],['現在の介入設定を保持しています。「同じ速度に揃える」で再設定できます。','Current interventions retained. Use Match speed to recalculate them.'],['基準 ','Baseline '],[' Hz → 目標 ',' Hz → target '],['カメラ推定（1フレーム差）','Camera estimate (frame difference)'],['欠測','Missing'],['固定子数','Stator count'],['駆動力','Motive force'],['回転抵抗 ζ','Rotational drag ζ'],['露光で像がリング化：速度推定は欠測。','Exposure blur: no reliable angular estimate.'],['撮影速度不足：折り返しで逆回転や減速に見えます。','Temporal aliasing: apparent reversal or slowdown is possible.'],['位置ノイズが回転半径に対して大きい条件です。','Position noise is large relative to the orbit radius.'],['＋ 推定重心','+ Estimated centroid'],['真の平均速度 / Hz','Mean model drift speed / Hz'],['カメラ平均速度 / Hz','Mean camera speed / Hz'],['平均固定子数','Mean stator count'],['平均駆動力 / mV','Mean motive force / mV'],['平均抵抗 / pN nm s','Mean drag / pN nm s'],['平均トルク / pN nm','Mean torque / pN nm'],['カメラ有効率 / %','Valid camera estimates / %'],['真の回転速度 / Hz','Model drift speed / Hz'],['カメラ推定速度 / Hz','Camera speed / Hz'],['イオン駆動力 / mV','Ion motive force / mV'],['回転抵抗 / pN nm s','Rotational drag / pN nm s'],['トルク / pN nm','Torque / pN nm'],
 ['カメラ推定速度の区間平均。欠測は除外。露光のぼけ・折り返しは補正していません。','Binned camera speed; missing estimates excluded. No blur or alias correction.'],['区間平均。背景の帯は介入期間、縦線は選択時刻。色は上の3条件に対応します。','Binned averages. Shading: intervention; vertical line: selected time. Colors match the conditions above.'],['平均区間 ','Bin width '],['速度推定なし：最初または直前のフレームが無効です。','No speed estimate: first frame or invalid preceding frame.']
 ];
 pairs.push(['バクテリアべん毛回転計測シミュレーター','Bacterial Flagellar Rotation Measurement Simulator'],['指定参考論文（数値フィット未実施）','Requested reference (no numerical fit)']);
 pairs.push(['ビーズアッセイでは、べん毛の短い部分にビーズを付け、顕微鏡でビーズの回転を追ってモーターの回転速度を推定します。','In a bead assay, a bead attached to a short flagellar segment is tracked under a microscope to estimate motor rotation speed.'],['介入による低速化を有効にする','Enable intervention-induced slowdown'],['介入とは、5〜20秒に駆動力・固定子数・負荷のいずれかを変える仮想操作です。オフでは全期間を基準条件で計算します。','An intervention changes motive force, stator count or load from 5 to 20 s. Off keeps baseline conditions throughout.'],['介入オフ：全期間で基準条件を使用します。','Intervention off: baseline conditions apply throughout.'],['実験条件CSVを読み込む','Import settings CSV'],['1行の設定値を読み込みます。','Import a single row of settings.'],['CSVテンプレート','CSV template'],['を参照してください。観測時系列の読み込みではありません。',' shows the columns. Observed time series cannot be imported.'],['条件を読み込みました。','Settings imported.'],['読み込み失敗：','Import failed: '],['JSON保存','Export JSON']);
 pairs.push(['5–20 s 基準（介入オフ）','5–20 s Baseline (intervention off)'],['介入オフ：基準条件の比較','Intervention off: baseline comparison'],['区間平均。介入オフのため背景の帯は表示しません。縦線は選択時刻です。','Binned averages. No intervention shading; the vertical line marks selected time.']);
 pairs.push(['モデル速度（ドリフト）','Model drift speed']);
 pairs.push(['確率的交換を有効にすると、単一軌跡の速度一致は崩れることがあります。同じ乱数シードで再計算し、基準区間の固定子数は8に固定します。','With stochastic exchange, speeds may differ across individual trajectories. Recompute with fixed seeds; baseline stator count starts at eight.'],['内向き駆動力が0のため、基準速度は0です。3原因の比較は成立しません。','Inward motive force is zero; baseline speed is zero. The three causes cannot be compared.'],['15–20秒のモデル平均（駆動力・固定子・負荷）：','Mean model speeds at 15–20 s (force / stators / load): '],['実現速度に差があります。確率的交換や手動設定を確認してください。','Realized speeds differ. Check stochastic exchange or manual settings.']);
 pairs.push(['トルク–スピード曲線','Torque–speed curves'],['選択時刻の設定値から計算した曲線と動作点です。時刻スライダー・再生・条件変更に連動します。','Curves and operating points use the settings at the selected time. They update with playback, the time slider and parameter changes.'],['kneeを持つ区分線形モデルによる曲線です。カメラ推定値ではなくモデルのドリフト速度を示します。CSVには曲線・負荷直線・動作点と設定値を含みます。','These curves use a piecewise-linear knee model. Points show model drift speed, not camera estimates. CSV includes motor curves, load lines, operating points and settings.']);
 const paragraphs=[
 'This phenomenological H⁺ motor model is not fitted to measurements from a particular species or mutant. It excludes Na⁺ coupling, directional switching, wall corrections, cell-body drag and hook elasticity.',
 'At 25 °C, define V = ψ(outside) − ψ(inside) and ΔpH = pH(inside) − pH(outside). Inward motive force P = max(0, V + 59.16 ΔpH) mV; p = P / 180.',
 "Default: a piecewise-linear knee model. τ₀ = 180Np, f₀ = 300p, fₖ = 0.65f₀. For 0 ≤ f ≤ fₖ, τ = τ₀(1 − 0.1f/fₖ); for fₖ < f ≤ f₀, τ = 0.9τ₀(f₀ − f)/(f₀ − fₖ); for f ≥ f₀, τ = 0. Solve the intersection with τ = 2πζf analytically in the appropriate segment. If P = 0 or N = 0, f = 0. The values 180 pN nm, 300 Hz, knee-speed ratio 0.65 and knee-torque ratio 0.9 are illustrative assumptions, not digitized or fitted values from the requested paper. Knee and no-load speeds scale with motive force and are assumed independent of stator count.",
 'For bead radius a, orbit radius r and viscosity η, ζ = 6πηar² + 8πηa³. Inputs in μm and mPa s give drag in pN nm s. The bead is rigidly coupled, orbiting and spinning at the same angular speed. No near-wall correction is included.',
 "Set f* = q fᵦ. Motive force becomes q times baseline; N* = 2πζf* / τ(1,p,f*); ζ* = τ(8,p,f*) / (2πf*), using the knee torque law above. By default deterministic mean-field exchange matches all three speeds. Enabling stochastic integer stators can substantially change the 15–20 s mean in a single trajectory. When motive force is zero the three causes cannot be distinguished.",
 'There are 11 sites. Binding rate: (11 − N)N* / (11tᵣ); unbinding rate: N(11 − N*) / (11tᵣ). The mean approaches N* with time constant tᵣ. Load-dependent recruitment and motive-force-dependent binding stability are deliberately uncoupled in this version. Rates are illustrative. Disabling stochastic exchange uses continuous mean-field relaxation; it does not stop exchange.',
 'Angular dynamics: dθ = 2πf dt + √(2kBT/ζ)dW, kBT = 4.116 pN nm. Model speed is the drift f, not a derivative of the thermally fluctuating angle. Internal step: 0.25 ms. Exposure integrates bead coordinates with trapezoidal weights; independent Gaussian localization noise is added to x and y. Camera speed uses the principal angle difference (−π to π), so |f| > fps/2 can alias. Frame pairs with normalized exposure-image radius below 0.15 are missing. This is not a full optical or photon-statistics model.',
 'Stator seeds: 12345, 23456, 34567. Thermal seeds add 199; camera seeds add 99. CSV contains frame timestamps, internal values, camera estimates and parameters. Outputs compare hypotheses; they do not diagnose experimental causes.'
 ];
 document.querySelectorAll('#model .modal > p').forEach((el,i)=>pairs.push([el.textContent,paragraphs[i]]));
 const note=document.querySelector('.view-note');pairs.push([note.textContent,'Top: fixed-axis motor diagram, angular motion slowed 100-fold. Bottom: exposure-integrated bead frame at the selected time. True rotation is counterclockwise viewed from outside the cell. No arrows.']);
 pairs.sort((a,b)=>b[0].length-a[0].length);
 function t(s){if(language==='ja')return s;for(const [ja,en] of pairs)s=s.split(ja).join(en);return s}
 function updateText(node){const old=saved.get(node);let original=old&&node.nodeValue===old.shown?old.original:node.nodeValue;const shown=t(original);if(node.nodeValue!==shown)node.nodeValue=shown;saved.set(node,{original,shown})}
 function apply(root=document.body){if(root.nodeType===3){if(!['SCRIPT','STYLE'].includes(root.parentElement?.tagName))updateText(root);return}if(root.nodeType!==1||['SCRIPT','STYLE'].includes(root.tagName))return;for(const attr of ['aria-label','title'])if(root.hasAttribute(attr)){let cache=attrs.get(root)||{};let old=cache[attr],value=root.getAttribute(attr),original=old&&value===old.shown?old.original:value,shown=t(original);if(value!==shown)root.setAttribute(attr,shown);cache[attr]={original,shown};attrs.set(root,cache)}for(const child of root.childNodes)apply(child)}
 const observer=new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')apply(r.target);else r.addedNodes.forEach(apply)}});
 function setLanguage(next){language=next;document.title='FlagellaScope — '+(next==='ja'?'バクテリアべん毛回転計測シミュレーター':'Bacterial Flagellar Rotation Measurement Simulator');document.documentElement.lang=next;apply();document.querySelector('#languageButton').textContent=next==='en'?'Japanese':'English';document.querySelector('#languageButton').setAttribute('aria-label',next==='en'?'Switch to Japanese':'英語に切り替え');if(typeof render==='function'){render();renderMatchStatus()}}
 const button=document.createElement('button');button.id='languageButton';button.type='button';document.querySelector('header').appendChild(button);button.onclick=()=>setLanguage(language==='en'?'ja':'en');
 apply();button.textContent='Japanese';button.setAttribute('aria-label','Switch to Japanese');document.documentElement.lang='en';observer.observe(document.body,{childList:true,characterData:true,subtree:true});
 return {t,setLanguage,get language(){return language}};
})();
